/* eslint-disable @typescript-eslint/ban-ts-comment */
    /* eslint-disable @typescript-eslint/no-explicit-any */
    // @ts-check
    // This file is autogenerated by scripts/build-registry.mts
    // Do not edit this file directly.
    
    import React from 'react';
    
    export const Index: Record<string, any> ={
      "audio-player": {
        name: "audio-player",
        description: "A minimal, theme-aware audio player component built for shadcn/ui, featuring play/pause controls, integrated progress visualization.",
        type: "registry:component",
        files: [{
        path: "src/registry/components/audio-player.tsx",
        type: "registry:component",
        }],
    },
    }