/* eslint-disable @typescript-eslint/ban-ts-comment */
    /* eslint-disable @typescript-eslint/no-explicit-any */
    // @ts-check
    // This file is autogenerated by scripts/build-registry.mts
    // Do not edit this file directly.
    
    import React from 'react';
    
    export const Index: Record<string, any> ={
      "audio-player": {
        name: "audio-player",
        description: "A minimal, theme-aware audio player component built for shadcn/ui, featuring play/pause controls, integrated progress visualization.",
        type: "registry:component",
        files: [{
        path: "src/registry/components/audio-player.tsx",
        type: "registry:component",
        }],
    },
      "social-icon": {
        name: "social-icon",
        description: "A set of social media icons with hover effects and theme-aware styling, built with shadcn/ui.",
        type: "registry:component",
        files: [{
        path: "src/registry/components/social-icon.tsx",
        type: "registry:component",
        }],
    },
      "placeholder-pattern": {
        name: "placeholder-pattern",
        description: "A minimal, theme-aware placeholder pattern component built for shadcn/ui.",
        type: "registry:ui",
        files: [{
        path: "src/registry/ui/placeholder-pattern.tsx",
        type: "registry:ui",
        }],
    },
      "corner-border-button": {
        name: "corner-border-button",
        description: "A corner border button component with animated corner borders",
        type: "registry:ui",
        files: [{
        path: "src/registry/ui/corner-border-button.tsx",
        type: "registry:ui",
        }],
    },
    }